Avtech/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from Home import views


urlpatterns = [
    path("admin/", admin.site.urls),
    path("", views.home, name="home"),
    path("project/", include("Project.urls")),
    path("home/", include("Home.urls")),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Home/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path("about/", views.about, name="about"),
    path("contact/", views.contact, name="contact"),
    path("services/", views.services, name="services"),
]

Project/urls.py
from django.urls import path
from . import views

app_name = "Project"


urlpatterns = [
    path("", views.project, name="project"),
    path("<int:Project_id>/", views.detail, name="detail"),
]

Home/models.py
from django.db import models
from django.contrib.auth.models import User


# Create your models here.
class About(models.Model):
    Name = models.CharField(max_length=50)
    Designation = models.CharField(max_length=50)
    Description = models.TextField(max_length=500, default="")
    Image = models.ImageField(upload_to="Home/images", default="")
    Facebook = models.URLField(blank=True)
    Insta = models.URLField(blank=True)
    Twitter = models.URLField(blank=True)

    def __str__(self):
        return self.Name


class ContactUs(models.Model):
    s_id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=50)
    email = models.CharField(max_length=100)
    content = models.TextField()
    date = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name

Project/models.py
from django.db import models
from datetime import datetime

# Create your models here.
class Project(models.Model):
    s_id = models.AutoField(primary_key=True)
    Title = models.CharField(max_length=50)
    Description = models.TextField(max_length=5000, default="")
    Image = models.ImageField(upload_to="Project/images", default="")
    Date = models.DateField()

    def __str__(self):
        return self.Title

Home/views.py
from django.shortcuts import render
from .models import About, ContactUs


def home(request):
    return render(request, "Home/index.html")


def about(request):
    abouts = About.objects.all()
    return render(request, "Home/about.html", {"abouts": abouts})


def services(request):
    return render(request, "Home/services.html")


def contact(request):

    if request.method == "POST":
        name = request.POST["name"]
        email = request.POST["email"]
        content = request.POST["content"]
        contact = ContactUs(name=name, email=email, content=content)
        contact.save()

    return render(request, "Home/contact.html")

Project/views.py
from django.shortcuts import render, get_object_or_404
from .models import Project


def project(request):
    projects = Project.objects.order_by("-Date")
    return render(request, "Project/project.html", {"projects": projects})


def detail(request, Project_id):
    projects = get_object_or_404(Project, pk=Project_id)
    return render(request, "Project/detail.html", {"projects": projects})

Home/templates/Home/about.html
{% extends 'Home/navbar.html' %} {%block content%}{%load static%}<!DOCTYPE html>
<html>
<head>
    <title>Our Team</title>

	<meta charset="utf-8" />
	<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />

    <link href="{% static "Home/bootstrap.css" %}" rel='stylesheet' />

    <link href="{% static "Home/pe-icon-7-stroke.css"%}" rel="stylesheet" />

<!--     <link href='css/ct-navbar.css' rel='stylesheet' /> -->
    <link href="{% static 'Home/rotating-card.css'%}" rel='stylesheet' />

    <meta content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0' name='viewport' />

    <link href="https://netdna.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css" rel="stylesheet">

    <script src="https://cdn.rawgit.com/google/code-prettify/master/loader/run_prettify.js"></script>
    <style>
        body{
            margin-top: 100px;
        }
        .navbar-default .navbar-nav > li > a{
            padding: 15px 15px;
            margin: 5px 0;
        }

        .navbar-default{
            padding: 10px 0;
            background-color: rgba(255, 255, 255, 0.95);
            border-color: transparent;
            box-shadow: 0 0px 13px rgba(0,0,0,.2);
        }
        .btn-info,
        .btn-info:hover,
        .btn-info:focus{
            color: #FFF !important;
            background-color: #00bbff !important;
            border-color: #00bbff !important;
        }

        .btn-info{
            opacity: .8;
            transition: all 0.1s;
            -webkit-transition: all 0.1s;
        }
        .btn-info:hover,
        .btn-info:focus{
            opacity: 1;
        }
    </style>
</head>
<div class="container">

    <div class="row">
        <h1 class="title">
            Our Team
            <br>
            <small>Present your team in an interesting way</small>
        </h1> 
        <div class="col-sm-10 col-sm-offset-1">{%for about in abouts%}
         <div class="col-md-4 col-sm-6">
             <div class="card-container">
                <div class="card">
                    <div class="front">
                        <div class="cover">
                            <img src="{% static "Home/architecture.jpg" %}"/> 


                        </div>
                        <div class="user">
                            <img class="img-circle" src="{{about.Image.url }}"/>
                        </div>
                        <div class="content">
                            <div class="main">
                                <h3 class="name">{{about.Name}}</h3>
                                <p class="profession">{{about.Designation}}</p>
                                
                            </div>
                            <div class="footer">
                                <i class="fa fa-mail-forward"></i> Auto Rotation
                            </div>
                        </div>
                    </div> <!-- end front panel -->
                    <div class="back">
                        <div class="content">
                            <div class="main">
                                <h4 class="text-center">{{about.Description}}</h4>
                                <p class="text-center"{{about.Description}}</p>

                                {% comment %} <div class="stats-container">
                                    <div class="stats">
                                        <h4>235</h4>
                                        <p>
                                            Followers
                                        </p>
                                    </div>
                                    <div class="stats">
                                        <h4>114</h4>
                                        <p>
                                            Following
                                        </p>
                                    </div>
                                    <div class="stats">
                                        <h4>35</h4>
                                        <p>
                                            Projects
                                        </p>
                                    </div>
                                </div> {% endcomment %}

                            </div>
                        </div>
                        <div class="footer">
                            <div class="social-links text-center">
                                <a href="https://creative-tim.com" class="facebook"><i class="fa fa-facebook fa-fw"></i></a>
                                <a href="https://creative-tim.com" class="google"><i class="fa fa-instagram fa-fw"></i></a>
                                <a href="https://creative-tim.com" class="twitter"><i class="fa fa-twitter fa-fw"></i></a>
                            </div>
                        </div>
                    </div> <!-- end back panel -->
                </div> <!-- end card -->
            </div> <!-- end card-container -->
        </div> <!-- end col sm 3 -->{%endfor%}


<script src="js/jquery-1.10.2.js" type="text/javascript"></script>
<script src="js/bootstrap.min.js" type="text/javascript"></script>

<script type="text/javascript">
    $().ready(function(){
        $('[rel="tooltip"]').tooltip();

        $('a.scroll-down').click(function(e){
            e.preventDefault();
            scroll_target = $(this).data('href');
             $('html, body').animate({
                 scrollTop: $(scroll_target).offset().top - 60
             }, 1000);
        });

    });

    function rotateCard(btn){
        var $card = $(btn).closest('.card-container');
        console.log($card);
        if($card.hasClass('hover')){
            $card.removeClass('hover');
        } else {
            $card.addClass('hover');
        }
    }


</script>

</body>
</html>{%endblock%}

Home/templates/Home/contact.html
{% extends 'Home/navbar.html' %} {%block content%}{%load static%}
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Contact Us</title>
    <link rel="stylesheet" href="{% static "Home/contactUs.css" %} " />
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.13.1/css/all.min.css"
    />
  </head>
  <body>
    <!--contact section start-->
    <div class="contact-section">
      <div class="contact-info">
        <div><i class="fas fa-map-marker-alt"></i>Lalitpur, Nepal</div>
        <div>
          <i class="fas fa-envelope"></i>engineering.avtechpvtltd@gmail.com
        </div>
        <div><i class="fas fa-phone"></i>+977-9866544277</div>
        <div><i class="fas fa-clock"></i>Sun - Fri 8:00 AM to 5:00 PM</div>
      </div>
      <div class="contact-form">
        <h2>Contact Us</h2>
        <form class="contact" action="{%url 'contact'%}" method="POST">
          {% csrf_token %}
          <input
            type="text"
            name="name"
            class="text-box"
            placeholder="Your Name"
            required
          />
          <input
            type="email"
            name="email"
            class="text-box"
            placeholder="Your Email"
            required
          />
          <textarea
            name="content"
            rows="5"
            placeholder="Your Message"
            required
          ></textarea>
          <input type="submit" name="submit" class="send-btn" value="Send" />
        </form>
      </div>
    </div>
    <!--contact section end-->
  </body>
</html>
{%endblock%}

Home/templates/Home/index.html
{% load static%}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>AVTECH COMPANY</title>
    <link rel="stylesheet" href="{% static "Home/style.css" %}" />
    <link rel="icon" type="image/png" href="{% static "Home/logo.png" %}">
    
  </head>
  <body>
    <div class="container">
      <div class="navbar">
        <div class="menu">
          <img height= '10%' width= '10%'src="{% static 'Home/logo.png' %}" class="rotate_01"/>
          <text style="color:white;"> AVTECH COMPANY PVT.LTD. </text>
          <div class="hamburger-menu">
            <div class="bar"></div>
          </div>
        </div>
      </div>

      <div class="main-container">
        <div class="main">
          <header>
            <div class="overlay">
              <div class="inner">  
                <h3 class="title">INNOVATION INTO DESIGN</h3>
                <p>
                  AVTECH COMPANY Pvt. Ltd. was established in 2015 by group of engineers with a goal to provide Professional and Ethical Engineering services for all.
                </p>
                <a href="{% url 'about'%}"><button class="btn">About Us</button></a>
                <pre> <h2 style="text-align:initial;">CONSTRUCTION |  DESIGN  |  SUPERVISION  |  3D MODELING  |  VALUATION</h2> </pre>
              </div>
            </div>
          </header>
        </div>
        

        <div class="shadow one"></div>
        <div class="shadow two"></div>
      </div>

      <div class="links">
        <ul>
          <li>
            <a href="{% url 'home'%}" style="--i: 0.05s">Home</a>
          </li>
          <li>
            <a href="{% url 'Project:project'%}" style="--i: 0.1s">Projects</a>
          </li>
          <li>
            <a href="{% url 'services'%}" style="--i: 0.15s">Services</a>
          </li>
          <li>
            <a href="{% url 'about'%}" style="--i: 0.25s">About Us</a>
          </li>
          <li>
            <a href="{% url 'contact'%}" style="--i: 0.3s">Contact Us</a>
          </li>
        </ul>
      </div>
    </div>

    <script src="{% static "Home/home.js" %}"></script>

  </body>
</html>

Home/templates/Home/navbar.html
{% load static%}
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="stylesheet" href="{% static "Home/navbar.css" %}" /> <link
    rel="icon" type="image/png" href="{% static "Home/logo.png" %}">
  </head>
  <body>
    <ul class="sidenav" id="nav">
      <li><a class="active" href="{% url 'home'%}">Home</a></li>
      <li><a href="{% url 'Project:project'%}">Projects</a></li>
      <li><a href="{% url 'services'%}">Services</a></li>
      <li><a href="{% url 'about'%}">About Us</a></li>
      <li><a href="{% url 'contact'%}">Contact Us</a></li>
    </ul>

    {%block content%}{%endblock%}
  </body>
</html>

Home/templates/Home/services.html
{% extends 'Home/navbar.html' %} {%block content%}{%load static%}
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8" />
    <title>Our Services</title>

    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <script
      src="https://kit.fontawesome.com/8b0e0499ed.js"
      crossorigin="anonymous"
    ></script>
    <link rel="stylesheet" href="{% static "Home/services.css" %}" />
  </head>
  <body>
    <div class="s-section">
      <div class="inner-width">
        <div class="s-title s-titles">Our Services</div>
        <div class="border"></div>
        <div class="s-container">
          <div class="s-box">
            <div class="s-icon">
              <i class="far fa-calendar-check"></i>
            </div>
            <div class="s-title">Project Formulation and Appraisal</div>
            <div class="s-desc">
              Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus
              pharetra, nibh a malesuada convallis, est elit laoreet nisl,
            </div>
          </div>
          <div class="s-box">
            <div class="s-icon">
              <i class="fas fa-search-location"></i>
            </div>
            <div class="s-title">Field Survey and Investigations</div>
            <div class="s-desc">
              Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus
              pharetra, nibh a malesuada convallis, est elit laoreet nisl,
            </div>
          </div>
          <div class="s-box">
            <div class="s-icon">
              <i class="fas fa-mail-bulk"></i>
            </div>
            <div class="s-title">Master Planning</div>
            <div class="s-desc">
              Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus
              pharetra, nibh a malesuada convallis, est elit laoreet nisl,
            </div>
          </div>
          <div class="s-box">
            <div class="s-icon">
              <i class="fas fa-tape"></i>
            </div>
            <div class="s-title">Architectural Planning & Design</div>
            <div class="s-desc">
              Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus
              pharetra, nibh a malesuada convallis, est elit laoreet nisl,
            </div>
          </div>
          <div class="s-box">
            <div class="s-icon">
              <i class="fas fa-hard-hat"></i>
            </div>
            <div class="s-title">Civil Engineering</div>
            <div class="s-desc">
              Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus
              pharetra, nibh a malesuada convallis, est elit laoreet nisl,
            </div>
          </div>
          <div class="s-box">
            <div class="s-icon">
              <i class="fas fa-ruler-combined"></i>
            </div>
            <div class="s-title">Structural Engineering and Design</div>
            <div class="s-desc">
              Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus
              pharetra, nibh a malesuada convallis, est elit laoreet nisl,
            </div>
          </div>
          <div class="s-box">
            <div class="s-icon">
              <i class="fas fa-tools"></i>
            </div>
            <div class="s-title">
              Structural Health Monitoring and Structural Assessment
            </div>
            <div class="s-desc">
              Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus
              pharetra, nibh a malesuada convallis, est elit laoreet nisl,
            </div>
          </div>
          <div class="s-box">
            <div class="s-icon">
              <i class="fas fa-drafting-compass"></i>
            </div>
            <div class="s-title">MEP Service Planning and Design</div>
            <div class="s-desc">
              Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus
              pharetra, nibh a malesuada convallis, est elit laoreet nisl,
            </div>
          </div>
          <div class="s-box">
            <div class="s-icon">
              <i class="fas fa-ruler"></i>
            </div>
            <div class="s-title">Interior Design</div>
            <div class="s-desc">
              Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus
              pharetra, nibh a malesuada convallis, est elit laoreet nisl,
            </div>
          </div>
          <div class="s-box">
            <div class="s-icon">
              <i class="fas fa-user-check"></i>
            </div>
            <div class="s-title">Preparation of Bidding Document</div>
            <div class="s-desc">
              Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus
              pharetra, nibh a malesuada convallis, est elit laoreet nisl,
            </div>
          </div>
          <div class="s-box">
            <div class="s-icon">
              <i class="fas fa-tasks"></i>
            </div>
            <div class="s-title">Project Management Services</div>
            <div class="s-desc">
              Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus
              pharetra, nibh a malesuada convallis, est elit laoreet nisl,
            </div>
          </div>
          <div class="s-box">
            <div class="s-icon">
              <i class="fas fa-search"></i>
            </div>
            <div class="s-title">Quantity Surveying</div>
            <div class="s-desc">
              Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus
              pharetra, nibh a malesuada convallis, est elit laoreet nisl,
            </div>
          </div>
          <div class="s-box">
            <div class="s-icon">
              <i class="fas fa-hands-helping"></i>
            </div>
            <div class="s-title">Supervision and Quality Control</div>
            <div class="s-desc">
              Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus
              pharetra, nibh a malesuada convallis, est elit laoreet nisl,
            </div>
          </div>
          <div class="s-box">
            <div class="s-icon">
              <i class="fas fa-pencil-ruler"></i>
            </div>
            <div class="s-title">
              Earthquake Engineering and Seismic vulnerability Assessment
            </div>
            <div class="s-desc">
              Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus
              pharetra, nibh a malesuada convallis, est elit laoreet nisl,
            </div>
          </div>
          <div class="s-box">
            <div class="s-icon">
              <i class="fas fa-toolbox"></i>
            </div>
            <div class="s-title">
              Construction management and Contract Administration
            </div>
            <div class="s-desc">
              Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus
              pharetra, nibh a malesuada convallis, est elit laoreet nisl,
            </div>
          </div>
        </div>
      </div>
    </div>
  </body>
</html>
{%endblock%}

Project/templates/Project/detail.html
{% extends 'Home/navbar.html'%} {% block content%}
<br />
<head>
  <style>
    body {
      font-family: "Poppins", sans-serif;
      background-image: linear-gradient(135deg, #ddf969 0%, #124653 74%);
      background-size: cover;
    }
  </style>
</head>
<body>
  <center>
    <h1 class="title">{{projects.Title}}</h1>

    <img src="{{ projects.Image.url }}" alt="tree" height="30%" width="40%" />

    <h2 style="color: white">{{projects.Date}}</h2>
    <p style="color: white">{{projects.Description|safe}}</p>
  </center>
</body>
{%endblock%}

Project/templates/Project/project.html
{% extends 'Home/navbar.html' %} {%block content%} {%load static%}<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <meta
      name="viewport"
      content="width=device-width, initial-scale=1, shrink-to-fit=no"
    />
    <title>Projects</title>
    <link href="{% static "Project/project.css" %}" rel='stylesheet' />
  </head>
  <body>
    <br /><br />
    <center><h1 class="title">
      Number of Project</h1><h1 class="title" id="typing">{{projects.count}} project{{projects.count|pluralize}}</h1>
    </h1></center>
    {%for project in projects%}
    <div class="blog-post">
      <div class="blog-post-img">
        <img src="{{ project.Image.url }}" alt="image" />
      </div>
      <div class="blog-post-info">
        <div class="blog-post-title">
          <h2>{{project.Title}}</h2>
        </div>
        <div class="blog-post-date">
          <span>{{project.Day}}</span>
          <span>{{project.Date}}</span>
        </div>
        <div class="blog-post-desc">
          <p>{{project.Description}}</p>
        </div>
        <div class="blog-post-read-more">
          <a href="{% url 'Project:detail' 1 %}">Read More</a>
        </div>
      </div>
    </div>
  </body>
  {%endfor%} {%endblock%}
</html>